# Dockerfile for building the stack

FROM dev.local/appsody/edge-sh

RUN microdnf install socat

# Copy the common components across into your stack filesystem (most stacks will need these)
COPY ./LICENSE /licenses/
COPY ./project /project
COPY ./config /config

EXPOSE 80